zone_id_mapping = {
    "Newark Airport, EWR": 1,
    "Jamaica Bay, Queens": 2,
    "Allerton/Pelham Gardens, Bronx": 3,
    "Alphabet City, Manhattan": 4,
    "Arden Heights, Staten Island": 5,
    "Arrochar/Fort Wadsworth, Staten Island": 6,
    "Astoria, Queens": 7,
    "Astoria Park, Queens": 8,
    "Auburndale, Queens": 9,
    "Baisley Park, Queens": 10,
    "Bath Beach, Brooklyn": 11,
    "Battery Park, Manhattan": 12,
    "Battery Park City, Manhattan": 13,
    "Bay Ridge, Brooklyn": 14,
    "Bay Terrace/Fort Totten, Queens": 15,
    "Bayside, Queens": 16,
    "Bedford, Brooklyn": 17,
    "Bedford Park, Bronx": 18,
    "Bellerose, Queens": 19,
    "Belmont, Bronx": 20,
    "Bensonhurst East, Brooklyn": 21,
    "Bensonhurst West, Brooklyn": 22,
    "Bloomfield/Emerson Hill, Staten Island": 23,
    "Bloomingdale, Manhattan": 24,
    "Boerum Hill, Brooklyn": 25,
    "Borough Park, Brooklyn": 26,
    "Breezy Point/Fort Tilden/Riis Beach, Queens": 27,
    "Briarwood/Jamaica Hills, Queens": 28,
    "Brighton Beach, Brooklyn": 29,
    "Broad Channel, Queens": 30,
    "Bronx Park, Bronx": 31,
    "Bronxdale, Bronx": 32,
    "Brooklyn Heights, Brooklyn": 33,
    "Brooklyn Navy Yard, Brooklyn": 34,
    "Brownsville, Brooklyn": 35,
    "Bushwick North, Brooklyn": 36,
    "Bushwick South, Brooklyn": 37,
    "Cambria Heights, Queens": 38,
    "Canarsie, Brooklyn": 39,
    "Carroll Gardens, Brooklyn": 40,
    "Central Harlem, Manhattan": 41,
    "Central Harlem North, Manhattan": 42,
    "Central Park, Manhattan": 43,
    "Charleston/Tottenville, Staten Island": 44,
    "Chinatown, Manhattan": 45,
    "City Island, Bronx": 46,
    "Claremont/Bathgate, Bronx": 47,
    "Clinton East, Manhattan": 48,
    "Clinton Hill, Brooklyn": 49,
    "Clinton West, Manhattan": 50,
    "Co-Op City, Bronx": 51,
    "Cobble Hill, Brooklyn": 52,
    "College Point, Queens": 53,
    "Columbia Street, Brooklyn": 54,
    "Coney Island, Brooklyn": 55,
    "Corona, Queens": 57,
    "Country Club, Bronx": 58,
    "Crotona Park, Bronx": 59,
    "Crotona Park East, Bronx": 60,
    "Crown Heights North, Brooklyn": 61,
    "Crown Heights South, Brooklyn": 62,
    "Cypress Hills, Brooklyn": 63,
    "Douglaston, Queens": 64,
    "Downtown Brooklyn/MetroTech, Brooklyn": 65,
    "DUMBO/Vinegar Hill, Brooklyn": 66,
    "Dyker Heights, Brooklyn": 67,
    "East Chelsea, Manhattan": 68,
    "East Concourse/Concourse Village, Bronx": 69,
    "East Elmhurst, Queens": 70,
    "East Flatbush/Farragut, Brooklyn": 71,
    "East Flatbush/Remsen Village, Brooklyn": 72,
    "East Flushing, Queens": 73,
    "East Harlem North, Manhattan": 74,
    "East Harlem South, Manhattan": 75,
    "East New York, Brooklyn": 76,
    "East New York/Pennsylvania Avenue, Brooklyn": 77,
    "East Tremont, Bronx": 78,
    "East Village, Manhattan": 79,
    "East Williamsburg, Brooklyn": 80,
    "Eastchester, Bronx": 81,
    "Elmhurst, Queens": 82,
    "Elmhurst/Maspeth, Queens": 83,
    "Eltingville/Annadale/Prince's Bay, Staten Island": 84,
    "Erasmus, Brooklyn": 85,
    "Far Rockaway, Queens": 86,
    "Financial District North, Manhattan": 87,
    "Financial District South, Manhattan": 88,
    "Flatbush/Ditmas Park, Brooklyn": 89,
    "Flatiron, Manhattan": 90,
    "Flatlands, Brooklyn": 91,
    "Flushing, Queens": 92,
    "Flushing Meadows-Corona Park, Queens": 93,
    "Fordham South, Bronx": 94,
    "Forest Hills, Queens": 95,
    "Forest Park/Highland Park, Queens": 96,
    "Fort Greene, Brooklyn": 97,
    "Fresh Meadows, Queens": 98,
    "Freshkills Park, Staten Island": 99,
    "Garment District, Manhattan": 100,
    "Glen Oaks, Queens": 101,
    "Glendale, Queens": 102,
    "Governor's Island/Ellis Island/Liberty Island, Manhattan": 105,
    "Gowanus, Brooklyn": 106,
    "Gramercy, Manhattan": 107,
    "Gravesend, Brooklyn": 108,
    "Great Kills, Staten Island": 109,
    "Great Kills Park, Staten Island": 110,
    "Green-Wood Cemetery, Brooklyn": 111,
    "Greenpoint, Brooklyn": 112,
    "Greenwich Village North, Manhattan": 113,
    "Greenwich Village South, Manhattan": 114,
    "Grymes Hill/Clifton, Staten Island": 115,
    "Hamilton Heights, Manhattan": 116,
    "Hammels/Arverne, Queens": 117,
    "Heartland Village/Todt Hill, Staten Island": 118,
    "Highbridge, Bronx": 119,
    "Highbridge Park, Manhattan": 120,
    "Hillcrest/Pomonok, Queens": 121,
    "Hollis, Queens": 122,
    "Homecrest, Brooklyn": 123,
    "Howard Beach, Queens": 124,
    "Hudson Sq, Manhattan": 125,
    "Hunts Point, Bronx": 126,
    "Inwood, Manhattan": 127,
    "Inwood Hill Park, Manhattan": 128,
    "Jackson Heights, Queens": 129,
    "Jamaica, Queens": 130,
    "Jamaica Estates, Queens": 131,
    "JFK Airport, Queens": 132,
    "Kensington, Brooklyn": 133,
    "Kew Gardens, Queens": 134,
    "Kew Gardens Hills, Queens": 135,
    "Kingsbridge Heights, Bronx": 136,
    "Kips Bay, Manhattan": 137,
    "LaGuardia Airport, Queens": 138,
    "Laurelton, Queens": 139,
    "Lenox Hill East, Manhattan": 140,
    "Lenox Hill West, Manhattan": 141,
    "Lincoln Square East, Manhattan": 142,
    "Lincoln Square West, Manhattan": 143,
    "Little Italy/NoLiTa, Manhattan": 144,
    "Long Island City/Hunters Point, Queens": 145,
    "Long Island City/Queens Plaza, Queens": 146,
    "Longwood, Bronx": 147,
    "Lower East Side, Manhattan": 148,
    "Madison, Brooklyn": 149,
    "Manhattan Beach, Brooklyn": 150,
    "Manhattan Valley, Manhattan": 151,
    "Manhattanville, Manhattan": 152,
    "Marble Hill, Manhattan": 153,
    "Marine Park/Floyd Bennett Field, Brooklyn": 154,
    "Marine Park/Mill Basin, Brooklyn": 155,
    "Mariners Harbor, Staten Island": 156,
    "Maspeth, Queens": 157,
    "Meatpacking/West Village West, Manhattan": 158,
    "Melrose South, Bronx": 159,
    "Middle Village, Queens": 160,
    "Midtown Center, Manhattan": 161,
    "Midtown East, Manhattan": 162,
    "Midtown North, Manhattan": 163,
    "Midtown South, Manhattan": 164,
    "Midwood, Brooklyn": 165,
    "Morningside Heights, Manhattan": 166,
    "Morrisania/Melrose, Bronx": 167,
    "Mott Haven/Port Morris, Bronx": 168,
    "Mount Hope, Bronx": 169,
    "Murray Hill, Manhattan": 170,
    "Murray Hill-Queens, Queens": 171,
    "New Dorp/Midland Beach, Staten Island": 172,
    "North Corona, Queens": 173,
    "Norwood, Bronx": 174,
    "Oakland Gardens, Queens": 175,
    "Oakwood, Staten Island": 176,
    "Ocean Hill, Brooklyn": 177,
    "Ocean Parkway South, Brooklyn": 178,
    "Old Astoria, Queens": 179,
    "Ozone Park, Queens": 180,
    "Park Slope, Brooklyn": 181,
    "Parkchester, Bronx": 182,
    "Pelham Bay, Bronx": 183,
    "Pelham Bay Park, Bronx": 184,
    "Pelham Parkway, Bronx": 185,
    "Penn Station/Madison Sq West, Manhattan": 186,
    "Port Richmond, Staten Island": 187,
    "Prospect-Lefferts Gardens, Brooklyn": 188,
    "Prospect Heights, Brooklyn": 189,
    "Prospect Park, Brooklyn": 190,
    "Queens Village, Queens": 191,
    "Queensboro Hill, Queens": 192,
    "Queensbridge/Ravenswood, Queens": 193,
    "Randalls Island, Manhattan": 194,
    "Red Hook, Brooklyn": 195,
    "Rego Park, Queens": 196,
    "Richmond Hill, Queens": 197,
    "Ridgewood, Queens": 198,
    "Rikers Island, Bronx": 199,
    "Riverdale/North Riverdale/Fieldston, Bronx": 200,
    "Rockaway Park, Queens": 201,
    "Roosevelt Island, Manhattan": 202,
    "Rosedale, Queens": 203,
    "Rossville/Woodrow, Staten Island": 204,
    "Saint Albans, Queens": 205,
    "Saint George/New Brighton, Staten Island": 206,
    "Saint Michaels Cemetery/Woodside, Queens": 207,
    "Schuylerville/Edgewater Park, Bronx": 208,
    "Seaport, Manhattan": 209,
    "Sheepshead Bay, Brooklyn": 210,
    "SoHo, Manhattan": 211,
    "Soundview/Bruckner, Bronx": 212,
    "Soundview/Castle Hill, Bronx": 213,
    "South Beach/Dongan Hills, Staten Island": 214,
    "South Jamaica, Queens": 215,
    "South Ozone Park, Queens": 216,
    "South Williamsburg, Brooklyn": 217,
    "Springfield Gardens North, Queens": 218,
    "Springfield Gardens South, Queens": 219,
    "Spuyten Duyvil/Kingsbridge, Bronx": 220,
    "Stapleton, Staten Island": 221,
    "Starrett City, Brooklyn": 222,
    "Steinway, Queens": 223,
    "Stuy Town/Peter Cooper Village, Manhattan": 224,
    "Stuyvesant Heights, Brooklyn": 225,
    "Sunnyside, Queens": 226,
    "Sunset Park East, Brooklyn": 227,
    "Sunset Park West, Brooklyn": 228,
    "Sutton Place/Turtle Bay North, Manhattan": 229,
    "Times Sq/Theatre District, Manhattan": 230,
    "TriBeCa/Civic Center, Manhattan": 231,
    "Two Bridges/Seward Park, Manhattan": 232,
    "UN/Turtle Bay South, Manhattan": 233,
    "Union Sq, Manhattan": 234,
    "University Heights/Morris Heights, Bronx": 235,
    "Upper East Side North, Manhattan": 236,
    "Upper East Side South, Manhattan": 237,
    "Upper West Side North, Manhattan": 238,
    "Upper West Side South, Manhattan": 239,
    "Van Cortlandt Park, Bronx": 240,
    "Van Cortlandt Village, Bronx": 241,
    "Van Nest/Morris Park, Bronx": 242,
    "Washington Heights North, Manhattan": 243,
    "Washington Heights South, Manhattan": 244,
    "West Brighton, Staten Island": 245,
    "West Chelsea/Hudson Yards, Manhattan": 246,
    "West Concourse, Bronx": 247,
    "West Farms/Bronx River, Bronx": 248,
    "West Village, Manhattan": 249,
    "Westchester Village/Unionport, Bronx": 250,
    "Westerleigh, Staten Island": 251,
    "Whitestone, Queens": 252,
    "Willets Point, Queens": 253,
    "Williamsbridge/Olinville, Bronx": 254,
    "Williamsburg (North Side), Brooklyn": 255,
    "Williamsburg (South Side), Brooklyn": 256,
    "Windsor Terrace, Brooklyn": 257,
    "Woodhaven, Queens": 258,
    "Woodlawn/Wakefield, Bronx": 259,
    "Woodside, Queens": 260,
    "World Trade Center, Manhattan": 261,
    "Yorkville East, Manhattan": 262,
    "Yorkville West, Manhattan": 263,
    "NV, Unknown": 264,
    "nan, Unknown": 265,
}
